
[phases.setup]
nixPkgs = ["python310", "postgresql", "gcc"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"]

[phases.build]
cmds = ["...", "python manage.py collectstatic --clear --noinput && python manage.py makemigrations && python manage.py migrate"]

[start]
cmd = "gunicorn mainserver.wsgi"