"""
Django settings for courseO_line project.

Generated by 'django-admin startproject' using Django 4.1.4.

"""

# Standard library
from pathlib import Path

# 3rd Party
from dotenv import load_dotenv

# local
from common.envcast import toStr, toBool, toInt


# courseO_line Project's BASE Directory
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

# Secret Key & Debug Mode
SECRET_KEY = toStr("SECRET_KEY")
DEBUG = toBool("DEBUG")

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "courseWebsite",
    "adminInterface",
    "administrator",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mainserver.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "Templates"
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mainserver.wsgi.application"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Database

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = "Static/"
STATICFILES_DIRS = [
    BASE_DIR / "Static"
]

MEDIA_URL = "Media/"
MEDIA_ROOT = BASE_DIR / "Media"


# Email Configuration

DEFAULT_FROM_EMAIL = toStr("DEFAULT_FROM_EMAIL")
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = toStr("EMAIL_HOST")
EMAIL_HOST_USER = toStr("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = toStr("EMAIL_HOST_PASSWORD")
EMAIL_PORT = toInt("EMAIL_PORT")
EMAIL_USE_TLS = toBool("EMAIL_USE_TLS")
